// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-upcoming-lessons.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_lessons_default = defineTool({
  name: "list_upcoming_lessons",
  title: "List upcoming lessons",
  description: "List the signed-in user's upcoming lessons (default: next 14 days), ordered by start time.",
  inputSchema: {
    days_ahead: z.number().int().min(1).max(90).default(14).describe("How many days ahead to look."),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days_ahead, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const now = /* @__PURE__ */ new Date();
    const until = new Date(now.getTime() + days_ahead * 864e5);
    const { data, error } = await supabaseForUser(ctx).from("lessons").select("id, starts_at, duration_minutes, subject, status, student_id, tutor_id, group_id").gte("starts_at", now.toISOString()).lte("starts_at", until.toISOString()).order("starts_at", { ascending: true }).limit(limit);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lessons: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-students.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_students_default = defineTool2({
  name: "list_students",
  title: "List students",
  description: "List students visible to the signed-in tutor/manager via their student_rates rows (subject + price per lesson).",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser2(ctx).from("student_rates").select("id, tutor_id, student_id, subject, price_per_lesson, currency").limit(limit);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { rates: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-pending-payments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pending_payments_default = defineTool3({
  name: "list_pending_payments",
  title: "List pending payments",
  description: "List lessons where the student payment is still pending (unpaid) \u2014 visible to the signed-in user via RLS.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser3(ctx).from("lesson_details_student").select("lesson_id, student_price, student_payment_status, student_paid_at, is_cancellation_fee").eq("student_payment_status", "pending").limit(limit);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { pending: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kficbcjqcbhqhjimxfed";
var mcp_default = defineMcp({
  name: "otutorhub-mcp",
  title: "oTutorHub MCP",
  version: "0.1.0",
  instructions: "Tools for oTutorHub: an online school management app. Use `list_upcoming_lessons` to see scheduled lessons, `list_students` to see the tutor/manager's student roster with rates, and `list_pending_payments` to see unpaid lessons. All tools act as the signed-in user (RLS-scoped).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_upcoming_lessons_default, list_students_default, list_pending_payments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
