// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { fetchWithTimeout } from './fetchWithTimeout';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
  // B7: таймаут 15с + бекоф-ретрай ідемпотентних читань — «вічний спінер у
  // метро» стає помилкою, яку ловлять catch/error-гілки. Якщо Lovable
  // регенерує цей файл і рядок зникне, впаде тест supabase-client-invariants.
  global: { fetch: fetchWithTimeout },
});